### ISSUE TITLE
Example VCF/BCF input file ?

### ISSUE THREAD

**Issue by lehuyduc** [rwk-unil/parallel_pbwt#1]
Hello, can you upload a big VCF/BCF files to the repo? It should be big to demonstrate more clearly the difference in speed between this version and others. It's also useful to see a reference benchmark on the repo.

Thanks!

**Comment by rwk-unil** [comment]
Hello,
I can't really upload a big data BCF for two reasons
1) The space on the repository is limited and not made for hosting binary files (I could host them somewhere ...)
2) Unless I make an artificial BCF, I cannot really share BCF files because of the data they contain may be confidential or copyrighted etc.

However, you can download chromosome 1 from the one thousand genome project (or all chromosomes and concat them to make an even bigger file)
You can download the data here : http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/
(More info here : https://www.internationalgenome.org/data-portal/data-collection/30x-grch38)

These files have multi-allelic sites so they require to be normalised to bi-allelic sites first (and I would suggest converting from .vcf.gz to .bcf to improve loading speed and reduce file size a bit).
If not normalised to bi-allelic sites, both my benchmark and [Durbin's PBWT software](https://github.com/richarddurbin/pbwt) will report an error on multi-allelic sites.

This can be done with the following command : 
```shell
# Split multi-allelic sites into bi-allelic sites and convert to BCF
bcftools norm -m -any <input_file.vcf.gz> -o <output_file.bcf> -Ob
```

To run the benchmark I provide you have to modify the filename in https://github.com/rwk-unil/parallel_pbwt/blob/main/main_bench.cpp
```c++
const std::string INPUT_FILE = "<filename.bcf>";
```
and recompile (I should have the benchmark take the file name as a parameter... but for now it is this way)

For the command line example tool you can directly run it (the output may be big because it reports the matches to text files, similar to [Durbin's PBWT software](https://github.com/richarddurbin/pbwt), with the difference that here one file per thread is generated, you can then concat the files in the right order given to get the same file as [Durbin's PBWT software](https://github.com/richarddurbin/pbwt)).

Let me know if you have any issues.
I hope the files from the one thousand genome project will be enough for you for testing.
Cheers,
Rick

**Comment by rwk-unil** [comment]
You can access benchmarks here : https://academic.oup.com/bioinformaticsadvances/advance-article/doi/10.1093/bioadv/vbad021/7067758?searchresult=1 (open access)
And in the supplementary materials [here](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformaticsadvances/PAP/10.1093_bioadv_vbad021/1/vbad021_supplementary_data.pdf?Expires=1680879246&Signature=wBB0jSpVf2CX~qYI6Fv-XKCfVTFn3QY~5JwjrvSJK0ttLt4p0X2JQG0EixpfgegeryOuXxIYGYp4wy3wrdiVbGVccMHurY8gaw2ijWZNCkEHzFl297n8IVxNApDO60wLBxquigX-Q1-w4c78z6Eml803S1SvOGQOqqTuksBDLkV7SFN8EnAam-ahMc3gWYsCO5CM4axZAzHiIPwpx-rG1cYEfZlQRn3vKNlx0EoeOFBWllU0P2pLF7hkCFvNtxKbwITsNn2f17mXT4UgVI~W8OVdTdjN24Jcv94VFHY5nrP4b-NaXwcTdsRV2xTu4nay-Bu75iL1~KFBggYlSHKacg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)

**Comment by lehuyduc** [comment]
Thanks for your detailed reply! I've emailed more information to your email at @unil.ch
